/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AES0907' at '6/8/16 10:14 AM' with Gradle 2.13
 *
 * @author AES0907, @date 6/8/16 10:14 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
